spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/orange?serverTimezone=GMT

  devtools:
    restart:
      exclude: static/**, public/**

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


  data:
    redis:
      host: 192.168.43.175 # 172.31.234.201 # 192.168.43.175

server:
  port: 8080